### ISSUE TITLE
How to find all ls and compile into js separately 

### ISSUE THREAD

**Issue by askucher** [DavidSouther/grunt-livescript#10]
Is it possible to find all *.ls and compile into *.js appropriate file in same directory?

**Comment by DavidSouther** [comment]
EG a one for one? Only way I can think of off hand is listing each by hand.

```
/foo
  /bar.ls
  /baz.ls
```

and your task config:

```
livescript: {
  buildtask: {
    files: {
      '/foo/bar.js': '/foo/bar.ls',
      '/foo/baz.js': '/foo/baz.js'
    }
  }
}
```

**Comment by chisui** [comment]
you can use `grunt.file.expandMapping`

    livescript:
      options:{+bare}
      files: grunt.file.expandMapping "**/*.ls" "your/dest" do
        cwd   : "your/dir"
        rename: -> "#{&0}/#{&1.replace /\.ls$/ \.js}"

**Comment by askucher** [comment]
Thx
